src/Zhongfu/BlogBundle/Entity/Image.php
<?php

namespace Zhongfu\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Image
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Zhongfu\BlogBundle\Entity\ImageRepository")
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Assert\NotBlank()
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(name="description", type="string", length=255)
     */
    private $description;

    /**
     * @var string
     * @Assert\Image(
     * mimeTypes = {"image/jpeg", "image/jpg","image/gif","image/png"},
     * mimeTypesMessage = "Choisissez une image valide")
     * @ORM\Column(name="file", type="string", length=255)
     */
    private $file;

    /**
     * @var string
     * @ORM\Column(name="path", type="string", length=255)
     */
    private $path;

    /**
     * @var Article
     * @ORM\ManyToOne(targetEntity="Article", cascade={"persist"})
     * @ORM\JoinColumn(name="article_id",referencedColumnName="id",onDelete="SET NULL")
     */
    private $article;

    /**
     * @var Evenement
     * @ORM\ManyToOne(targetEntity="Evenement", cascade={"persist"})
     * @ORM\JoinColumn(name="evenement_id",referencedColumnName="id",onDelete="SET NULL")
     */
    private $evenement;

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get Evenement
     *
     * @return Evenement
     */
    public function getEvenement()
    {
        return $this->evenement;
    }

    /**
     * Set Evenement
     * @param Evenement $evenement
     *
     * @return Evenement
     */
    public function setEvenement($evenement)
    {
        $this->evenement = $evenement;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Image
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set file
     *
     * @param string $file
     * @return Image
     */
    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }

    /**
     * Get file
     *
     * @return string 
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Image
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set article
     *
     * @param Article $article
     * @return Article
     */
    public function setArticle($article)
    {
        $this->article = $article;

        return $this;
    }

    /**
     * Get Article
     *
     * @return Article
     */
    public function getArticle()
    {
        return $this->article;
    }

    public function getUrl()
    {
        return $this->getPath().'/'. $this->getFile();
    }

    public function getMiniUrl()
    {
        return $this->getPath().'/mini_'. $this->getFile();
    }
}

src/Zhongfu/BlogBundle/Controller/IncludesController.php
<?php

namespace Zhongfu\BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Zhongfu\BlogBundle\Form\SendEmailContactType;
use Zhongfu\BlogBundle\Entity\SendEmailContact;

class IncludesController extends Controller
{
    /**
     * @Template()
     */
    public function navigationAction($oCategory = null)
    {
        $aTypes = $this->getDoctrine()->getManager()->getRepository('ZhongfuBlogBundle:Type')->findAll();
        $aLinks = $this->getDoctrine()->getManager()->getRepository('ZhongfuBlogBundle:Link')->findAll();

        if ($oCategory != null) {
            return ['category' => $oCategory, 'types' => $aTypes, 'links' => $aLinks];
        } else {
            return ['types' => $aTypes, 'links' => $aLinks];
        }
    }

    /**
     * @Template()
     */
    public function footerAction()
    {
        return [];
    }

    /**
     * @Template()
     */
    public function carouselAction()
    {
        return [];
    }

    /**
     * @Template()
     */
    public function relatedPostsAction($oPost)
    {
        $oEntityManager = $this->getDoctrine()->getManager();

        $query = $oEntityManager->createQuery('SELECT a FROM ZhongfuBlogBundle:Article a WHERE a.id != :id and a.type = :type')
            ->setParameter('id', $oPost->getId())
            ->setParameter('type', $oPost->getType());
        $aArticles = $query->getResult();

        $query = $oEntityManager->createQuery('SELECT a FROM ZhongfuBlogBundle:Evenement a WHERE a.id != :id and a.type != :type')
            ->setParameter('id', $oPost->getId())
            ->setParameter('type', $oPost->getType());
        $aEvenements = $query->getResult();


        return ['articles' => $aArticles, 'evenements' => $aEvenements];
    }

    /**
     * @Template()
     */
    public function enVedetteAction()
    {
        $oEntityManager = $this->getDoctrine()->getManager();
        $query = $oEntityManager->createQuery('SELECT a FROM ZhongfuBlogBundle:Article a WHERE a.is_vedette = TRUE ');
        $aArticles = $query->getResult();
        $query = $oEntityManager->createQuery('SELECT a FROM ZhongfuBlogBundle:Evenement a WHERE a.is_vedette = TRUE ');
        $aEvenements = $query->getResult();

        $aPosts = array_merge($aArticles, $aEvenements);

        return ['posts' => $aPosts];
    }

    /**
     * @Template()
     */
    public function contactAction()
    {
        $oSendEmailContact = new SendEmailContact();
        $oForm = $this->createForm(new SendEmailContactType(), $oSendEmailContact);


        $aContacts = $this->getDoctrine()->getManager()->getRepository('ZhongfuBlogBundle:Contact')->findAll();
        return ['contacts' => $aContacts, 'form' => $oForm->createView()];
    }

    /**
     * @Template()
     */
    public function coursAction()
    {
        return [];
    }

}

src/Zhongfu/BlogBundle/Resources/views/Includes/carousel.html.twig
{#<div class="container">#}
    <div id="carousel-example-generic" class="carousel slide hidden-xs" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides image 1200*315 -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="{{ asset('images/carouselle/carouselle1.png') }}" alt="...">

                <div class="carousel-caption">
                    <h3>Le Qi Gong, un art interne</h3>
                </div>
            </div>
            <div class="item">
                <img src="{{ asset('images/carouselle/carouselle2.jpg') }}" alt="...">

                <div class="carousel-caption">
                    <h3>Beaucoup de partage en Qi gong</h3>
                </div>
            </div>
            <div class="item">
                <img src="{{ asset('images/carouselle/carouselle3.jpg') }}" alt="...">

                <div class="carousel-caption">
                    <h3>Un instant zen...</h3>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="fa fa-chevron-left fa-2x  glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="fa fa-chevron-right fa-2x  glyphicon-chevron-right"></span>
        </a>
    </div>
    <!-- Carousel -->
{#</div>#}

src/Zhongfu/BlogBundle/Resources/views/Includes/contact.html.twig
<div class="modal fade" id="ContactModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="modal-title">Pour nous contacter</h3>
            </div>
            <div class="modal-body">
                <div class="hidden-sm hidden-xs">
                    <table class="table" id="tblGrid">
                        <thead id="tblHead">
                        <tr>
                            <th>Prénom</th>
                            <th>Nom</th>
                            <th><span class="fa fa- fa-user fa-lg"></span> Role</th>
                            <th><span class="fa fa-phone fa-lg"></span> Téléphone</th>
                            <th><span class="fa fa-envelope fa-lg"></span> Email</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for contact in contacts %}
                            <tr>
                                <td>{{ contact.firstname|capitalize }}</td>
                                <td>{{ contact.lastname|capitalize }}</td>
                                <td>{{ contact.role|capitalize }}</td>
                                <td>{{ contact.phone }}</td>
                                <td><a href="mailto:{{ contact.email }}"> {{ contact.email }}</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="hidden-lg hidden-md">
                    {% for contact in contacts %}
                        <div class="panel panel-primary">
                            <div class="panel-heading">{{ contact.firstname|capitalize }} {{ contact.lastname|capitalize }}</div>
                            <div class="panel-body">
                                <ul class="list-inline">
                                    <li><span class="fa fa-phone fa-lg"></span> {{ contact.phone }}</li>
                                    <li><span class="fa fa-envelope fa-lg"></span><a
                                                href="mailto:{{ contact.email }}"> {{ contact.email }}</a></li>
                                    <li><span class="fa fa- fa-user fa-lg"></span> {{ contact.role }}</li>
                                </ul>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                <h3 class="modal-title" >Par formulaire</h3>

                {{ form_start(form) }}
                {{ form_errors(form) }}

                <div class="form-group">
                    <div class="col-md-6">
                        {{ form_label(form.firstname,"Prénom :") }}
                        {{ form_widget(form.firstname,{attr:{'size':'15','class':'form-control'}}) }}
                        {{ form_errors(form.firstname) }}
                    </div>

                    <div class="col-md-6">
                        {{ form_label(form.lastname,"Nom :") }}
                        {{ form_widget(form.lastname,{attr:{'size':'15','class':'form-control'}}) }}
                        {{ form_errors(form.lastname) }}
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-6">
                        {{ form_label(form.email,"Email :") }}
                        {{ form_widget(form.email,{attr:{'class':'form-control'}}) }}
                        {{ form_errors(form.email) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_label(form.phone,"Téléphone :") }}
                        {{ form_widget(form.phone,{attr:{'class':'form-control'}}) }}
                        {{ form_errors(form.phone) }}
                    </div>
                </div>

                <div class="form-group">
                    {{ form_label(form.subject,"Sujet:") }}
                    {{ form_widget(form.subject,{attr:{'class':'form-control'}}) }}
                    {{ form_errors(form.subject) }}
                </div>

                <div class="form-group">
                    {{ form_label(form.content,"Message:") }}
                    {{ form_widget(form.content,{attr:{'class':'form-control','rows':'8'}}) }}
                    {{ form_errors(form.content) }}
                </div>
            </div>
            <div class="modal-footer">
                {{ form_widget(form.save,{'attr':{'class': 'btn btn-primary'},'label':'Envoyer'}) }}
                {{ form_rest(form) }}
                {{ form_end(form) }}
                <button type="button" class="btn btn-default " data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
    <!-- /.modal-content -->
</div>
<!-- /.modal-dialog -->
</div><!-- /.modal -->

src/Zhongfu/BlogBundle/Resources/views/Includes/cours.html.twig
<div class="modal fade" id="CoursModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="modal-title">Cours hebdomadaires</h3>
            </div>
            <div class="modal-body">

                <div class="panel panel-primary">
                    <div class="panel-heading"><h4 style="text-align: center">Centre culturel “Les Cigales"</h4><h6
                                style="text-align: center">33, avenue des Pyrénées - Anglet</h6></div>
                    <div class="panel-body">

                        <h3>Lundi</h3>
                        <table class="table table-responsive">
                            <tr>
                                <td class="hour-cours">8h30 - 9h30</td>
                                <td>(débutants) cours d’initiation vers le Qi Gong avec Ana NOUVEAU (50 euros par trimestre)
                                </td>
                            </tr>
                            <tr>
                                <td class="hour-cours">9h - 20h 30</td>
                                <td>(débutants) Tai Ji Quan style Chen : Laojia</td>
                            </tr>
                            <tr>
                                <td class="hour-cours">20h 30 - 21h</td>
                                <td>(confirmés) : Laojia - Tuishou (longue forme)</td>
                            </tr>
                        </table>
                        <h3>Mardi</h3>
                        <table class="table table-responsive">
                            <tr>
                                <td class="hour-cours">19h - 20h 30</td>
                                <td>Forme Hui Chun Gong (débutants) (TAOLU)</td>
                            </tr>
                            <tr>
                                <td class="hour-cours">20h 30 - 21h</td>
                                <td>TAOLU méditation Hui Chun Gong (confirmés)</td>
                            </tr>
                        </table>
                        <h3>Mercredi</h3>
                        <table class="table table-responsive">
                            <tr>
                                <td class="hour-cours">17h 15 - 18h 30</td>
                                <td>Initiation au taijiquan style Chen suivi des étirements jusqu’à 19 h 00 .</td>
                            </tr>
                            <tr>
                                <td class="hour-cours">18 h 30 à 20 h 00</td>
                                <td>Qi Gong : Etirements dans l’ouverture (ouvert, gratuit, pour tous inscrits à un cours hebdomadaire) ou faisant partie d’un cours complet de qi gong …de 19 h15  à 20 h 00 : Qi gong : Le pas du Tigre .</td>
                            </tr>
                        </table>
                    </div>
                </div>

                <div class="panel panel-success">
                    <div class="panel-heading"><h4 style="text-align: center">Paroisse Trinité</h4><h6
                                style="text-align: center">88, rue de Hardoy - Anglet</h6></div>
                    <div class="panel-body">
                        <h3>Lundi</h3>
                        <table class="table table-responsive">
                            <tr>
                                <td class="hour-cours">10h - 11h 30</td>
                                <td>Forme de Qi Gong Hui Chun Gong (TAOLU).</td>
                            </tr>
                        </table>
                        <h3>Mardi</h3>
                        <table class="table table-responsive">
                            <tr>
                                <td class="hour-cours">10 h - 11 h 30</td>
                                <td>Qi Gong de l’oie blanche et petit bâton.</td>
                            </tr>
                        </table>
                        <h3>Jeudi</h3>
                        <table class="table table-responsive">
                            <tr>
                                <td class="hour-cours">10h - 11h30</td>
                                <td>Qi Gong Nei Yang Gong.</td>
                            </tr>
                        </table>

                        <em>Pour les débutants, les deux premiers cours sont gratuits et sans engagement.</em><br>
                        <br>
                        <em>La cotisation est <strong>annuelle</strong> et en cours d’année <strong>trimestrielle</strong>: 270 euros par an ou 90 euros par trimestre en cours d’année   (pour un cours hebdomadaire)  - 15 % pour les couples  - 30 % pour les + de 15ans -  Accès à tous les cours après règlement de 420 euros de cotisations par an.</em><br>
                        <br>
                        <em>Les adhésions, assurance (43 euros) et la licence (33 euros) sont en sus : soit 76 euros pour cette saison 2015-2016.</em><br>
                        <br>
                        <em>Les stages seront ponctuels , voir sur l’actualité du site . Merci</em>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.modal-content -->

<!-- /.modal-dialog -->
<!-- /.modal -->

src/Zhongfu/BlogBundle/Resources/views/Includes/enVedette.html.twig
<div id="myCarousel" class="carousel slide hidden-sm" data-ride="carousel">
    <!-- Indicators -->
    {% for post in posts %}
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="{{ loop.index0 }}"
                {% if loop.index0 == 0 %}class="active" {% endif %}></li>
        </ol>
    {% endfor %}

    <!-- Wrapper for slides -->
    <div class="panel" id="en-vedette">
        <div class="panel-body">
        <div class="carousel-inner carousel-vedette" role="listbox">
            {% for post in posts %}
                <div class=" carousel-vedette-item item {% if loop.index0 == 0 %}active{% endif %}">
                    <img src="{{ asset(post.avatar.miniUrl) }}" alt="{{ post.avatar.name }}">
                    <h3 class="">{{ post.titre }}</h3>
                    <p>{{ post.slug }}</p>
                </div>
            {% endfor %}
        </div>
        </div>
    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

src/Zhongfu/BlogBundle/Resources/views/Includes/footer.html.twig
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="footer_inner">
                    <p class="pull-left">Tout droit réservé <a href="#">ZhongFu</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

src/Zhongfu/BlogBundle/Resources/views/Includes/navigation.html.twig
<div class="container">
    <!-- Static navbar -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ path ('_homepage') }}"><span>ZhongFu.eu</span></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav custom_nav">
                    <li class=""><a href="{{ path ('_homepage') }}">Accueil</a></li>
                    <li data-toggle="modal" data-target="#CoursModal" style="cursor: pointer"><a>Cours à l'année</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories</a>
                        <ul class="dropdown-menu" role="menu">
                            {% for category in types %}
                                <li>
                                    <a href="{{ path('_categoryHome',{"category" : category.url}) }}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Médias
                            & Archives</a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ path('_imagesArchives') }}">Photos et images</a></li>
                            {#<li><a href="#">Videos</a></li>#}
                            <li><a href="{{ path('_articlesArchives') }}">Articles</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Liens</a>
                        <ul class="dropdown-menu" role="menu">
                            {% for link in links %}
                            <li><a href="{{ link.url }}"><strong>{{ link.name }}</strong>: {{ link.description }} </a></li>
                            {% endfor %}
                        </ul>
                    </li>

                    <li data-toggle="modal" data-target="#ContactModal"  style="cursor: pointer"><a>Contact</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!--/.container-fluid -->
    </nav>
    {#<form id="searchForm">#}
    {#<input type="text" placeholder="Cherchez...">#}
    {#<input type="submit" value="">#}
    {#</form>#}
</div>

src/Zhongfu/BlogBundle/Resources/views/Includes/relatedPosts.html.twig
<div class="panel panel-primary" id="panel-related-articles">
    <div class="panel-heading">
        <h3 class="panel-title related-articles-panel-title">Articles qui pourrait vous intéresser : </h3>
    </div>
    <div class="panel-body">
        <table class="table table-condensed">
            {% for post in articles %}
                <tr>
                    <td><a href="{{ path('_UniqueArticle',{'id':post.id,'category':post.type.url}) }}">{{ post.titre }}</a></td>
                    <td>Ajouté le: {{ post.date|localizeddate('long', 'none', global_locale ) }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="panel panel-success" id="panel-related-articles">
    <div class="panel-heading">
        <h3 class="panel-title related-articles-panel-title">Evénements à découvrir : </h3>
    </div>
    <div class="panel-body">
        <table class="table table-condensed">
            {% for post in evenements %}
                <tr>
                    <td><a href="{{ path('_UniqueArticle',{'id':post.id,'category':post.type.url}) }}">{{ post.titre }}</a></td>
                    <td>Ajouté le: {{ post.date|localizeddate('long', 'none', global_locale ) }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>